# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0e\x66rauddetection\">\n\x15\x42ookSuggestionRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x15\n\rboughtBookIds\x18\x02 \x03(\t\"\xa6\x01\n\x16\x42ookSuggestionResponse\x12L\n\x0esuggestedBooks\x18\x01 \x03(\x0b\x32\x34.frauddetection.BookSuggestionResponse.SuggestedBook\x1a>\n\rSuggestedBook\x12\x0e\n\x06\x62ookId\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t2s\n\x12SuggestionsService\x12]\n\x0cSuggestBooks\x12%.frauddetection.BookSuggestionRequest\x1a&.frauddetection.BookSuggestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOKSUGGESTIONREQUEST']._serialized_start=37
  _globals['_BOOKSUGGESTIONREQUEST']._serialized_end=99
  _globals['_BOOKSUGGESTIONRESPONSE']._serialized_start=102
  _globals['_BOOKSUGGESTIONRESPONSE']._serialized_end=268
  _globals['_BOOKSUGGESTIONRESPONSE_SUGGESTEDBOOK']._serialized_start=206
  _globals['_BOOKSUGGESTIONRESPONSE_SUGGESTEDBOOK']._serialized_end=268
  _globals['_SUGGESTIONSSERVICE']._serialized_start=270
  _globals['_SUGGESTIONSSERVICE']._serialized_end=385
# @@protoc_insertion_point(module_scope)
