# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0e\x66rauddetection\"I\n\x0fSuggestionsData\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x15\n\rboughtBookIds\x18\x03 \x03(\t\"\x1f\n\x1dInitializeRequestDataResponse\"(\n\x15\x42ookSuggestionRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\"\xa6\x01\n\x16\x42ookSuggestionResponse\x12L\n\x0esuggestedBooks\x18\x01 \x03(\x0b\x32\x34.frauddetection.BookSuggestionResponse.SuggestedBook\x1a>\n\rSuggestedBook\x12\x0e\n\x06\x62ookId\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\".\n\x1b\x43learSuggestionsDataRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\"\x1e\n\x1c\x43learSuggestionsDataResponse2\xc4\x02\n\x12SuggestionsService\x12g\n\x15InitializeRequestData\x12\x1f.frauddetection.SuggestionsData\x1a-.frauddetection.InitializeRequestDataResponse\x12]\n\x0cSuggestBooks\x12%.frauddetection.BookSuggestionRequest\x1a&.frauddetection.BookSuggestionResponse\x12\x66\n\tClearData\x12+.frauddetection.ClearSuggestionsDataRequest\x1a,.frauddetection.ClearSuggestionsDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUGGESTIONSDATA']._serialized_start=37
  _globals['_SUGGESTIONSDATA']._serialized_end=110
  _globals['_INITIALIZEREQUESTDATARESPONSE']._serialized_start=112
  _globals['_INITIALIZEREQUESTDATARESPONSE']._serialized_end=143
  _globals['_BOOKSUGGESTIONREQUEST']._serialized_start=145
  _globals['_BOOKSUGGESTIONREQUEST']._serialized_end=185
  _globals['_BOOKSUGGESTIONRESPONSE']._serialized_start=188
  _globals['_BOOKSUGGESTIONRESPONSE']._serialized_end=354
  _globals['_BOOKSUGGESTIONRESPONSE_SUGGESTEDBOOK']._serialized_start=292
  _globals['_BOOKSUGGESTIONRESPONSE_SUGGESTEDBOOK']._serialized_end=354
  _globals['_CLEARSUGGESTIONSDATAREQUEST']._serialized_start=356
  _globals['_CLEARSUGGESTIONSDATAREQUEST']._serialized_end=402
  _globals['_CLEARSUGGESTIONSDATARESPONSE']._serialized_start=404
  _globals['_CLEARSUGGESTIONSDATARESPONSE']._serialized_end=434
  _globals['_SUGGESTIONSSERVICE']._serialized_start=437
  _globals['_SUGGESTIONSSERVICE']._serialized_end=761
# @@protoc_insertion_point(module_scope)
