# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verification/verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fverification/verification.proto\x12\x0cverification\"#\n\x10\x43learDataRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\"5\n\x1dInitializeRequestDataResponse\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\x08\"\x1d\n\nVerifyData\x12\x0f\n\x07orderId\x18\x01 \x01(\t\"3\n\x14VerificationResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\xd1\x01\n\x13VerificationRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12 \n\x04user\x18\x02 \x01(\x0b\x32\x12.verification.User\x12*\n\torderData\x18\x03 \x01(\x0b\x32\x17.verification.OrderData\x12,\n\ncreditCard\x18\x04 \x01(\x0b\x32\x18.verification.CreditCard\x12-\n\x07\x62illing\x18\x05 \x01(\x0b\x32\x1c.verification.BillingAddress\"%\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"\x9d\x01\n\tOrderData\x12\x35\n\norderItems\x18\x01 \x03(\x0b\x32!.verification.OrderData.OrderItem\x12\x14\n\x0c\x64iscountCode\x18\x02 \x01(\t\x12\x16\n\x0eshippingMethod\x18\x03 \x01(\t\x1a+\n\tOrderItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"A\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"[\n\x0e\x42illingAddress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t2\xda\x02\n\x06Verify\x12^\n\x15InitializeRequestData\x12!.verification.VerificationRequest\x1a\".verification.VerificationResponse\x12O\n\x0fVerifyOrderData\x12\x18.verification.VerifyData\x1a\".verification.VerificationResponse\x12N\n\x0eVerifyUserData\x12\x18.verification.VerifyData\x1a\".verification.VerificationResponse\x12O\n\tClearData\x12\x1e.verification.ClearDataRequest\x1a\".verification.VerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'verification.verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLEARDATAREQUEST']._serialized_start=49
  _globals['_CLEARDATAREQUEST']._serialized_end=84
  _globals['_INITIALIZEREQUESTDATARESPONSE']._serialized_start=86
  _globals['_INITIALIZEREQUESTDATARESPONSE']._serialized_end=139
  _globals['_VERIFYDATA']._serialized_start=141
  _globals['_VERIFYDATA']._serialized_end=170
  _globals['_VERIFICATIONRESPONSE']._serialized_start=172
  _globals['_VERIFICATIONRESPONSE']._serialized_end=223
  _globals['_VERIFICATIONREQUEST']._serialized_start=226
  _globals['_VERIFICATIONREQUEST']._serialized_end=435
  _globals['_USER']._serialized_start=437
  _globals['_USER']._serialized_end=474
  _globals['_ORDERDATA']._serialized_start=477
  _globals['_ORDERDATA']._serialized_end=634
  _globals['_ORDERDATA_ORDERITEM']._serialized_start=591
  _globals['_ORDERDATA_ORDERITEM']._serialized_end=634
  _globals['_CREDITCARD']._serialized_start=636
  _globals['_CREDITCARD']._serialized_end=701
  _globals['_BILLINGADDRESS']._serialized_start=703
  _globals['_BILLINGADDRESS']._serialized_end=794
  _globals['_VERIFY']._serialized_start=797
  _globals['_VERIFY']._serialized_end=1143
# @@protoc_insertion_point(module_scope)
