# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import verification_pb2 as verification__pb2


class VerifyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckOrder = channel.unary_unary(
                '/verification.Verify/CheckOrder',
                request_serializer=verification__pb2.Order.SerializeToString,
                response_deserializer=verification__pb2.verificationResponse.FromString,
                )


class VerifyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VerifyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOrder,
                    request_deserializer=verification__pb2.Order.FromString,
                    response_serializer=verification__pb2.verificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verification.Verify', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Verify(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/verification.Verify/CheckOrder',
            verification__pb2.Order.SerializeToString,
            verification__pb2.verificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
