# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import verification_pb2 as verification__pb2


class VerifyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeRequestData = channel.unary_unary(
                '/verification.Verify/InitializeRequestData',
                request_serializer=verification__pb2.VerificationRequest.SerializeToString,
                response_deserializer=verification__pb2.VerificationResponse.FromString,
                )
        self.VerifyOrderData = channel.unary_unary(
                '/verification.Verify/VerifyOrderData',
                request_serializer=verification__pb2.VerifyData.SerializeToString,
                response_deserializer=verification__pb2.VerificationResponse.FromString,
                )
        self.VerifyUserData = channel.unary_unary(
                '/verification.Verify/VerifyUserData',
                request_serializer=verification__pb2.VerifyData.SerializeToString,
                response_deserializer=verification__pb2.VerificationResponse.FromString,
                )
        self.ClearData = channel.unary_unary(
                '/verification.Verify/ClearData',
                request_serializer=verification__pb2.ClearDataRequest.SerializeToString,
                response_deserializer=verification__pb2.VerificationResponse.FromString,
                )


class VerifyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeRequestData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOrderData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VerifyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeRequestData': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeRequestData,
                    request_deserializer=verification__pb2.VerificationRequest.FromString,
                    response_serializer=verification__pb2.VerificationResponse.SerializeToString,
            ),
            'VerifyOrderData': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOrderData,
                    request_deserializer=verification__pb2.VerifyData.FromString,
                    response_serializer=verification__pb2.VerificationResponse.SerializeToString,
            ),
            'VerifyUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyUserData,
                    request_deserializer=verification__pb2.VerifyData.FromString,
                    response_serializer=verification__pb2.VerificationResponse.SerializeToString,
            ),
            'ClearData': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearData,
                    request_deserializer=verification__pb2.ClearDataRequest.FromString,
                    response_serializer=verification__pb2.VerificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verification.Verify', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Verify(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeRequestData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/verification.Verify/InitializeRequestData',
            verification__pb2.VerificationRequest.SerializeToString,
            verification__pb2.VerificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyOrderData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/verification.Verify/VerifyOrderData',
            verification__pb2.VerifyData.SerializeToString,
            verification__pb2.VerificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/verification.Verify/VerifyUserData',
            verification__pb2.VerifyData.SerializeToString,
            verification__pb2.VerificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/verification.Verify/ClearData',
            verification__pb2.ClearDataRequest.SerializeToString,
            verification__pb2.VerificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
