# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fraud_detection_pb2 as fraud__detection__pb2


class FraudDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeRequestData = channel.unary_unary(
                '/frauddetection.FraudDetectionService/InitializeRequestData',
                request_serializer=fraud__detection__pb2.FraudDetectionData.SerializeToString,
                response_deserializer=fraud__detection__pb2.InitializeRequestDataResponse.FromString,
                )
        self.DetectFraudQuick = channel.unary_unary(
                '/frauddetection.FraudDetectionService/DetectFraudQuick',
                request_serializer=fraud__detection__pb2.QuickFraudDetectionRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.QuickFraudDetectionResponse.FromString,
                )
        self.DetectFraudComprehensive = channel.unary_unary(
                '/frauddetection.FraudDetectionService/DetectFraudComprehensive',
                request_serializer=fraud__detection__pb2.ComprehensiveFraudDetectionRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.ComprehensiveFraudDetectionResponse.FromString,
                )
        self.ClearData = channel.unary_unary(
                '/frauddetection.FraudDetectionService/ClearData',
                request_serializer=fraud__detection__pb2.ClearFraudDetectionDataRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.ClearFraudDetectionDataResponse.FromString,
                )


class FraudDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeRequestData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectFraudQuick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectFraudComprehensive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeRequestData': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeRequestData,
                    request_deserializer=fraud__detection__pb2.FraudDetectionData.FromString,
                    response_serializer=fraud__detection__pb2.InitializeRequestDataResponse.SerializeToString,
            ),
            'DetectFraudQuick': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFraudQuick,
                    request_deserializer=fraud__detection__pb2.QuickFraudDetectionRequest.FromString,
                    response_serializer=fraud__detection__pb2.QuickFraudDetectionResponse.SerializeToString,
            ),
            'DetectFraudComprehensive': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFraudComprehensive,
                    request_deserializer=fraud__detection__pb2.ComprehensiveFraudDetectionRequest.FromString,
                    response_serializer=fraud__detection__pb2.ComprehensiveFraudDetectionResponse.SerializeToString,
            ),
            'ClearData': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearData,
                    request_deserializer=fraud__detection__pb2.ClearFraudDetectionDataRequest.FromString,
                    response_serializer=fraud__detection__pb2.ClearFraudDetectionDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'frauddetection.FraudDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FraudDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeRequestData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/frauddetection.FraudDetectionService/InitializeRequestData',
            fraud__detection__pb2.FraudDetectionData.SerializeToString,
            fraud__detection__pb2.InitializeRequestDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DetectFraudQuick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/frauddetection.FraudDetectionService/DetectFraudQuick',
            fraud__detection__pb2.QuickFraudDetectionRequest.SerializeToString,
            fraud__detection__pb2.QuickFraudDetectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DetectFraudComprehensive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/frauddetection.FraudDetectionService/DetectFraudComprehensive',
            fraud__detection__pb2.ComprehensiveFraudDetectionRequest.SerializeToString,
            fraud__detection__pb2.ComprehensiveFraudDetectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/frauddetection.FraudDetectionService/ClearData',
            fraud__detection__pb2.ClearFraudDetectionDataRequest.SerializeToString,
            fraud__detection__pb2.ClearFraudDetectionDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
