# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leader_selection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16leader_selection.proto\x12\x10leader_selection\"F\n\rLeaderDeclare\x12\x12\n\nsenderUUID\x18\x01 \x01(\t\x12\x13\n\x0bsender_name\x18\x02 \x01(\t\x12\x0c\n\x04term\x18\x03 \x01(\x05\"\x04\n\x02OK\"0\n\x11HealthDeclaration\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"D\n\x0bVoteRequest\x12\x12\n\nsenderUUID\x18\x01 \x01(\t\x12\x13\n\x0bsender_name\x18\x02 \x01(\t\x12\x0c\n\x04term\x18\x03 \x01(\x05\"M\n\x0cVoteResponse\x12\x12\n\nsenderUUID\x18\x01 \x01(\t\x12\x13\n\x0bsender_name\x18\x02 \x01(\t\x12\x14\n\x0c\x63onfirmation\x18\x03 \x01(\x08\x32\xee\x01\n\tSelection\x12H\n\x0bHealthCheck\x12#.leader_selection.HealthDeclaration\x1a\x14.leader_selection.OK\x12O\n\x0eGetVoteRequest\x12\x1d.leader_selection.VoteRequest\x1a\x1e.leader_selection.VoteResponse\x12\x46\n\rDeclareLeader\x12\x1f.leader_selection.LeaderDeclare\x1a\x14.leader_selection.OKb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'leader_selection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LEADERDECLARE']._serialized_start=44
  _globals['_LEADERDECLARE']._serialized_end=114
  _globals['_OK']._serialized_start=116
  _globals['_OK']._serialized_end=120
  _globals['_HEALTHDECLARATION']._serialized_start=122
  _globals['_HEALTHDECLARATION']._serialized_end=170
  _globals['_VOTEREQUEST']._serialized_start=172
  _globals['_VOTEREQUEST']._serialized_end=240
  _globals['_VOTERESPONSE']._serialized_start=242
  _globals['_VOTERESPONSE']._serialized_end=319
  _globals['_SELECTION']._serialized_start=322
  _globals['_SELECTION']._serialized_end=560
# @@protoc_insertion_point(module_scope)
