# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import leader_selection_pb2 as leader__selection__pb2


class SelectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/leader_selection.Selection/HealthCheck',
                request_serializer=leader__selection__pb2.HealthDeclaration.SerializeToString,
                response_deserializer=leader__selection__pb2.OK.FromString,
                )
        self.GetVoteRequest = channel.unary_unary(
                '/leader_selection.Selection/GetVoteRequest',
                request_serializer=leader__selection__pb2.VoteRequest.SerializeToString,
                response_deserializer=leader__selection__pb2.VoteResponse.FromString,
                )
        self.DeclareLeader = channel.unary_unary(
                '/leader_selection.Selection/DeclareLeader',
                request_serializer=leader__selection__pb2.LeaderDeclare.SerializeToString,
                response_deserializer=leader__selection__pb2.OK.FromString,
                )


class SelectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVoteRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclareLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SelectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=leader__selection__pb2.HealthDeclaration.FromString,
                    response_serializer=leader__selection__pb2.OK.SerializeToString,
            ),
            'GetVoteRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVoteRequest,
                    request_deserializer=leader__selection__pb2.VoteRequest.FromString,
                    response_serializer=leader__selection__pb2.VoteResponse.SerializeToString,
            ),
            'DeclareLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclareLeader,
                    request_deserializer=leader__selection__pb2.LeaderDeclare.FromString,
                    response_serializer=leader__selection__pb2.OK.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'leader_selection.Selection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Selection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/leader_selection.Selection/HealthCheck',
            leader__selection__pb2.HealthDeclaration.SerializeToString,
            leader__selection__pb2.OK.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVoteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/leader_selection.Selection/GetVoteRequest',
            leader__selection__pb2.VoteRequest.SerializeToString,
            leader__selection__pb2.VoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeclareLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/leader_selection.Selection/DeclareLeader',
            leader__selection__pb2.LeaderDeclare.SerializeToString,
            leader__selection__pb2.OK.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
