# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verification/verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fverification/verification.proto\x12\x0cverification\"\x90\x03\n\x13verificationRequest\x1a%\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\x1a\xb1\x01\n\tOrderData\x12I\n\norderItems\x18\x01 \x03(\x0b\x32\x35.verification.verificationRequest.OrderData.OrderItem\x12\x14\n\x0c\x64iscountCode\x18\x02 \x01(\t\x12\x16\n\x0eshippingMethod\x18\x03 \x01(\t\x1a+\n\tOrderItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x1a\x41\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\x1a[\n\x0e\x42illingAddress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"=\n\x14verificationResponse\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x11\n\tstatusMsg\x18\x02 \x01(\t2]\n\x06Verify\x12S\n\nCheckOrder\x12!.verification.verificationRequest\x1a\".verification.verificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'verification.verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VERIFICATIONREQUEST']._serialized_start=50
  _globals['_VERIFICATIONREQUEST']._serialized_end=450
  _globals['_VERIFICATIONREQUEST_USER']._serialized_start=73
  _globals['_VERIFICATIONREQUEST_USER']._serialized_end=110
  _globals['_VERIFICATIONREQUEST_ORDERDATA']._serialized_start=113
  _globals['_VERIFICATIONREQUEST_ORDERDATA']._serialized_end=290
  _globals['_VERIFICATIONREQUEST_ORDERDATA_ORDERITEM']._serialized_start=247
  _globals['_VERIFICATIONREQUEST_ORDERDATA_ORDERITEM']._serialized_end=290
  _globals['_VERIFICATIONREQUEST_CREDITCARD']._serialized_start=292
  _globals['_VERIFICATIONREQUEST_CREDITCARD']._serialized_end=357
  _globals['_VERIFICATIONREQUEST_BILLINGADDRESS']._serialized_start=359
  _globals['_VERIFICATIONREQUEST_BILLINGADDRESS']._serialized_end=450
  _globals['_VERIFICATIONRESPONSE']._serialized_start=452
  _globals['_VERIFICATIONRESPONSE']._serialized_end=513
  _globals['_VERIFY']._serialized_start=515
  _globals['_VERIFY']._serialized_end=608
# @@protoc_insertion_point(module_scope)
