# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue/queue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from verification import verification_pb2 as verification_dot_verification__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11queue/queue.proto\x12\x05queue\x1a\x1fverification/verification.proto\"0\n\x11OrderConfirmation\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x0e\n\x0cOrderRequest2\x92\x01\n\x05Queue\x12\x46\n\x07\x45nqueue\x12!.verification.VerificationRequest\x1a\x18.queue.OrderConfirmation\x12\x41\n\x07\x44\x65queue\x12\x13.queue.OrderRequest\x1a!.verification.VerificationRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue.queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERCONFIRMATION']._serialized_start=61
  _globals['_ORDERCONFIRMATION']._serialized_end=109
  _globals['_ORDERREQUEST']._serialized_start=111
  _globals['_ORDERREQUEST']._serialized_end=125
  _globals['_QUEUE']._serialized_start=128
  _globals['_QUEUE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
