# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from executor import executor_pb2 as executor_dot_executor__pb2
from verification import verification_pb2 as verification_dot_verification__pb2


class ExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteOrder = channel.unary_unary(
                '/executor.Executor/ExecuteOrder',
                request_serializer=executor_dot_executor__pb2.OrderRequest.SerializeToString,
                response_deserializer=verification_dot_verification__pb2.VerificationRequest.FromString,
                )


class ExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteOrder,
                    request_deserializer=executor_dot_executor__pb2.OrderRequest.FromString,
                    response_serializer=verification_dot_verification__pb2.VerificationRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'executor.Executor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Executor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/executor.Executor/ExecuteOrder',
            executor_dot_executor__pb2.OrderRequest.SerializeToString,
            verification_dot_verification__pb2.VerificationRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
