# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/executor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from verification import verification_pb2 as verification_dot_verification__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65xecutor/executor.proto\x12\x08\x65xecutor\x1a\x1fverification/verification.proto\"\x0e\n\x0cOrderRequest2U\n\x08\x45xecutor\x12I\n\x0c\x45xecuteOrder\x12\x16.executor.OrderRequest\x1a!.verification.VerificationRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor.executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERREQUEST']._serialized_start=70
  _globals['_ORDERREQUEST']._serialized_end=84
  _globals['_EXECUTOR']._serialized_start=86
  _globals['_EXECUTOR']._serialized_end=171
# @@protoc_insertion_point(module_scope)
